services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - regis-net
      
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - regis-net

networks:
  regis-net:
    driver: bridge